### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Models.Configuration.ResourceProviders
  commentId: N:FoundationaLLM.Common.Models.Configuration.ResourceProviders
  id: ResourceProviders
  parent: FoundationaLLM.Common.Models.Configuration
  children:
  - FoundationaLLM.Common.Models.Configuration.ResourceProviders.ResourceProviderCacheSettings
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.Models.Configuration.ResourceProviders
  nameWithType: FoundationaLLM.Common.Models.Configuration.ResourceProviders
  fullName: FoundationaLLM.Common.Models.Configuration.ResourceProviders
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.Models.Configuration.ResourceProviders.ResourceProviderCacheSettings
  commentId: T:FoundationaLLM.Common.Models.Configuration.ResourceProviders.ResourceProviderCacheSettings
  parent: FoundationaLLM.Common.Models.Configuration.ResourceProviders
  href: FoundationaLLM.Common.Models.Configuration.ResourceProviders.ResourceProviderCacheSettings.html
  name: ResourceProviderCacheSettings
  nameWithType: ResourceProviderCacheSettings
  fullName: FoundationaLLM.Common.Models.Configuration.ResourceProviders.ResourceProviderCacheSettings
- uid: FoundationaLLM.Common.Models.Configuration.ResourceProviders
  commentId: N:FoundationaLLM.Common.Models.Configuration.ResourceProviders
  href: FoundationaLLM.html
  name: FoundationaLLM.Common.Models.Configuration.ResourceProviders
  nameWithType: FoundationaLLM.Common.Models.Configuration.ResourceProviders
  fullName: FoundationaLLM.Common.Models.Configuration.ResourceProviders
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Models
    name: Models
    href: FoundationaLLM.Common.Models.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration
    name: Configuration
    href: FoundationaLLM.Common.Models.Configuration.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration.ResourceProviders
    name: ResourceProviders
    href: FoundationaLLM.Common.Models.Configuration.ResourceProviders.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Models
    name: Models
    href: FoundationaLLM.Common.Models.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration
    name: Configuration
    href: FoundationaLLM.Common.Models.Configuration.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration.ResourceProviders
    name: ResourceProviders
    href: FoundationaLLM.Common.Models.Configuration.ResourceProviders.html
