### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Models.Configuration.Authentication
  commentId: N:FoundationaLLM.Common.Models.Configuration.Authentication
  id: Authentication
  parent: FoundationaLLM.Common.Models.Configuration
  children:
  - FoundationaLLM.Common.Models.Configuration.Authentication.EntraSettings
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.Models.Configuration.Authentication
  nameWithType: FoundationaLLM.Common.Models.Configuration.Authentication
  fullName: FoundationaLLM.Common.Models.Configuration.Authentication
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.Models.Configuration.Authentication.EntraSettings
  commentId: T:FoundationaLLM.Common.Models.Configuration.Authentication.EntraSettings
  href: FoundationaLLM.Common.Models.Configuration.Authentication.EntraSettings.html
  name: EntraSettings
  nameWithType: EntraSettings
  fullName: FoundationaLLM.Common.Models.Configuration.Authentication.EntraSettings
