### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  commentId: N:FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  id: DataSourceConfigurations
  parent: FoundationaLLM.Common.Models.Orchestration
  children:
  - FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.BlobStorageConfiguration
  - FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.CXOConfiguration
  - FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.SQLDatabaseConfiguration
  - FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.SearchServiceConfiguration
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  nameWithType: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  fullName: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.BlobStorageConfiguration
  commentId: T:FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.BlobStorageConfiguration
  parent: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  href: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.BlobStorageConfiguration.html
  name: BlobStorageConfiguration
  nameWithType: BlobStorageConfiguration
  fullName: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.BlobStorageConfiguration
- uid: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.CXOConfiguration
  commentId: T:FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.CXOConfiguration
  parent: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  href: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.CXOConfiguration.html
  name: CXOConfiguration
  nameWithType: CXOConfiguration
  fullName: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.CXOConfiguration
- uid: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.SQLDatabaseConfiguration
  commentId: T:FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.SQLDatabaseConfiguration
  parent: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  href: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.SQLDatabaseConfiguration.html
  name: SQLDatabaseConfiguration
  nameWithType: SQLDatabaseConfiguration
  fullName: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.SQLDatabaseConfiguration
- uid: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.SearchServiceConfiguration
  commentId: T:FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.SearchServiceConfiguration
  parent: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  href: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.SearchServiceConfiguration.html
  name: SearchServiceConfiguration
  nameWithType: SearchServiceConfiguration
  fullName: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.SearchServiceConfiguration
- uid: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  commentId: N:FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  href: FoundationaLLM.html
  name: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  nameWithType: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  fullName: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Models
    name: Models
    href: FoundationaLLM.Common.Models.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Orchestration
    name: Orchestration
    href: FoundationaLLM.Common.Models.Orchestration.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
    name: DataSourceConfigurations
    href: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Models
    name: Models
    href: FoundationaLLM.Common.Models.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Orchestration
    name: Orchestration
    href: FoundationaLLM.Common.Models.Orchestration.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations
    name: DataSourceConfigurations
    href: FoundationaLLM.Common.Models.Orchestration.DataSourceConfigurations.html
