### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.OpenAPI
  commentId: N:FoundationaLLM.Common.OpenAPI
  id: OpenAPI
  parent: FoundationaLLM.Common
  children:
  - FoundationaLLM.Common.OpenAPI.ConfigureSwaggerOptions
  - FoundationaLLM.Common.OpenAPI.SwaggerDefaultValues
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.OpenAPI
  nameWithType: FoundationaLLM.Common.OpenAPI
  fullName: FoundationaLLM.Common.OpenAPI
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.OpenAPI.ConfigureSwaggerOptions
  commentId: T:FoundationaLLM.Common.OpenAPI.ConfigureSwaggerOptions
  href: FoundationaLLM.Common.OpenAPI.ConfigureSwaggerOptions.html
  name: ConfigureSwaggerOptions
  nameWithType: ConfigureSwaggerOptions
  fullName: FoundationaLLM.Common.OpenAPI.ConfigureSwaggerOptions
- uid: FoundationaLLM.Common.OpenAPI.SwaggerDefaultValues
  commentId: T:FoundationaLLM.Common.OpenAPI.SwaggerDefaultValues
  href: FoundationaLLM.Common.OpenAPI.SwaggerDefaultValues.html
  name: SwaggerDefaultValues
  nameWithType: SwaggerDefaultValues
  fullName: FoundationaLLM.Common.OpenAPI.SwaggerDefaultValues
