### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Models.Configuration.KeyVault
  commentId: N:FoundationaLLM.Common.Models.Configuration.KeyVault
  id: KeyVault
  parent: FoundationaLLM.Common.Models.Configuration
  children:
  - FoundationaLLM.Common.Models.Configuration.KeyVault.KeyVaultSecretEntry
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.Models.Configuration.KeyVault
  nameWithType: FoundationaLLM.Common.Models.Configuration.KeyVault
  fullName: FoundationaLLM.Common.Models.Configuration.KeyVault
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.Models.Configuration.KeyVault.KeyVaultSecretEntry
  commentId: T:FoundationaLLM.Common.Models.Configuration.KeyVault.KeyVaultSecretEntry
  href: FoundationaLLM.Common.Models.Configuration.KeyVault.KeyVaultSecretEntry.html
  name: KeyVaultSecretEntry
  nameWithType: KeyVaultSecretEntry
  fullName: FoundationaLLM.Common.Models.Configuration.KeyVault.KeyVaultSecretEntry
