### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Configuration.Models
  commentId: N:FoundationaLLM.Configuration.Models
  id: Models
  parent: FoundationaLLM.Configuration
  children:
  - FoundationaLLM.Configuration.Models.APIEndpointReference
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Configuration.Models
  nameWithType: FoundationaLLM.Configuration.Models
  fullName: FoundationaLLM.Configuration.Models
  type: Namespace
  assemblies:
  - FoundationaLLM.Configuration
references:
- uid: FoundationaLLM.Configuration.Models.APIEndpointReference
  commentId: T:FoundationaLLM.Configuration.Models.APIEndpointReference
  href: FoundationaLLM.Configuration.Models.APIEndpointReference.html
  name: APIEndpointReference
  nameWithType: APIEndpointReference
  fullName: FoundationaLLM.Configuration.Models.APIEndpointReference
