### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Configuration.Validation
  commentId: N:FoundationaLLM.Configuration.Validation
  id: Validation
  parent: FoundationaLLM.Configuration
  children:
  - FoundationaLLM.Configuration.Validation.ConfigurationHealthChecks
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Configuration.Validation
  nameWithType: FoundationaLLM.Configuration.Validation
  fullName: FoundationaLLM.Configuration.Validation
  type: Namespace
  assemblies:
  - FoundationaLLM.Configuration
references:
- uid: FoundationaLLM.Configuration.Validation.ConfigurationHealthChecks
  commentId: T:FoundationaLLM.Configuration.Validation.ConfigurationHealthChecks
  href: FoundationaLLM.Configuration.Validation.ConfigurationHealthChecks.html
  name: ConfigurationHealthChecks
  nameWithType: ConfigurationHealthChecks
  fullName: FoundationaLLM.Configuration.Validation.ConfigurationHealthChecks
