### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions
  commentId: N:FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions
  id: ConfigurationOptions
  parent: FoundationaLLM.Orchestration.Core.Models
  children:
  - FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.LangChainServiceSettings
  - FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.OrchestrationServiceSettings
  - FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.SemanticKernelServiceSettings
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions
  nameWithType: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions
  fullName: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions
  type: Namespace
  assemblies:
  - FoundationaLLM.Orchestration.Core
references:
- uid: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.LangChainServiceSettings
  commentId: T:FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.LangChainServiceSettings
  href: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.LangChainServiceSettings.html
  name: LangChainServiceSettings
  nameWithType: LangChainServiceSettings
  fullName: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.LangChainServiceSettings
- uid: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.OrchestrationServiceSettings
  commentId: T:FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.OrchestrationServiceSettings
  href: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.OrchestrationServiceSettings.html
  name: OrchestrationServiceSettings
  nameWithType: OrchestrationServiceSettings
  fullName: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.OrchestrationServiceSettings
- uid: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.SemanticKernelServiceSettings
  commentId: T:FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.SemanticKernelServiceSettings
  href: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.SemanticKernelServiceSettings.html
  name: SemanticKernelServiceSettings
  nameWithType: SemanticKernelServiceSettings
  fullName: FoundationaLLM.Orchestration.Core.Models.ConfigurationOptions.SemanticKernelServiceSettings
