### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Models.Configuration.Authorization
  commentId: N:FoundationaLLM.Common.Models.Configuration.Authorization
  id: Authorization
  parent: FoundationaLLM.Common.Models.Configuration
  children:
  - FoundationaLLM.Common.Models.Configuration.Authorization.AuthorizationServiceClientSettings
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.Models.Configuration.Authorization
  nameWithType: FoundationaLLM.Common.Models.Configuration.Authorization
  fullName: FoundationaLLM.Common.Models.Configuration.Authorization
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.Models.Configuration.Authorization.AuthorizationServiceClientSettings
  commentId: T:FoundationaLLM.Common.Models.Configuration.Authorization.AuthorizationServiceClientSettings
  parent: FoundationaLLM.Common.Models.Configuration.Authorization
  href: FoundationaLLM.Common.Models.Configuration.Authorization.AuthorizationServiceClientSettings.html
  name: AuthorizationServiceClientSettings
  nameWithType: AuthorizationServiceClientSettings
  fullName: FoundationaLLM.Common.Models.Configuration.Authorization.AuthorizationServiceClientSettings
- uid: FoundationaLLM.Common.Models.Configuration.Authorization
  commentId: N:FoundationaLLM.Common.Models.Configuration.Authorization
  href: FoundationaLLM.html
  name: FoundationaLLM.Common.Models.Configuration.Authorization
  nameWithType: FoundationaLLM.Common.Models.Configuration.Authorization
  fullName: FoundationaLLM.Common.Models.Configuration.Authorization
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Models
    name: Models
    href: FoundationaLLM.Common.Models.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration
    name: Configuration
    href: FoundationaLLM.Common.Models.Configuration.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration.Authorization
    name: Authorization
    href: FoundationaLLM.Common.Models.Configuration.Authorization.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Models
    name: Models
    href: FoundationaLLM.Common.Models.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration
    name: Configuration
    href: FoundationaLLM.Common.Models.Configuration.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration.Authorization
    name: Authorization
    href: FoundationaLLM.Common.Models.Configuration.Authorization.html
