### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Models.Configuration.ContentSafety
  commentId: N:FoundationaLLM.Common.Models.Configuration.ContentSafety
  id: ContentSafety
  parent: FoundationaLLM.Common.Models.Configuration
  children:
  - FoundationaLLM.Common.Models.Configuration.ContentSafety.AzureContentSafetySettings
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.Models.Configuration.ContentSafety
  nameWithType: FoundationaLLM.Common.Models.Configuration.ContentSafety
  fullName: FoundationaLLM.Common.Models.Configuration.ContentSafety
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.Models.Configuration.ContentSafety.AzureContentSafetySettings
  commentId: T:FoundationaLLM.Common.Models.Configuration.ContentSafety.AzureContentSafetySettings
  href: FoundationaLLM.Common.Models.Configuration.ContentSafety.AzureContentSafetySettings.html
  name: AzureContentSafetySettings
  nameWithType: AzureContentSafetySettings
  fullName: FoundationaLLM.Common.Models.Configuration.ContentSafety.AzureContentSafetySettings
