### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Constants.Configuration
  commentId: N:FoundationaLLM.Common.Constants.Configuration
  id: Configuration
  parent: FoundationaLLM.Common.Constants
  children:
  - FoundationaLLM.Common.Constants.Configuration.APIEndpointProviders
  - FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeyFilters
  - FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeySections
  - FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeys
  - FoundationaLLM.Common.Constants.Configuration.AuthorizationDependencyInjectionKeys
  - FoundationaLLM.Common.Constants.Configuration.AuthorizationKeyVaultSecretNames
  - FoundationaLLM.Common.Constants.Configuration.ConfigurationOptions
  - FoundationaLLM.Common.Constants.Configuration.DependencyInjectionKeys
  - FoundationaLLM.Common.Constants.Configuration.EnvironmentTypes
  - FoundationaLLM.Common.Constants.Configuration.EnvironmentVariables
  - FoundationaLLM.Common.Constants.Configuration.KeyVaultSecretNames
  - FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames
  - FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSets
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.Constants.Configuration
  nameWithType: FoundationaLLM.Common.Constants.Configuration
  fullName: FoundationaLLM.Common.Constants.Configuration
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.Constants.Configuration.APIEndpointProviders
  commentId: T:FoundationaLLM.Common.Constants.Configuration.APIEndpointProviders
  href: FoundationaLLM.Common.Constants.Configuration.APIEndpointProviders.html
  name: APIEndpointProviders
  nameWithType: APIEndpointProviders
  fullName: FoundationaLLM.Common.Constants.Configuration.APIEndpointProviders
- uid: FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeyFilters
  commentId: T:FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeyFilters
  href: FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeyFilters.html
  name: AppConfigurationKeyFilters
  nameWithType: AppConfigurationKeyFilters
  fullName: FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeyFilters
- uid: FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeySections
  commentId: T:FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeySections
  href: FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeySections.html
  name: AppConfigurationKeySections
  nameWithType: AppConfigurationKeySections
  fullName: FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeySections
- uid: FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeys
  commentId: T:FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeys
  href: FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeys.html
  name: AppConfigurationKeys
  nameWithType: AppConfigurationKeys
  fullName: FoundationaLLM.Common.Constants.Configuration.AppConfigurationKeys
- uid: FoundationaLLM.Common.Constants.Configuration.AuthorizationDependencyInjectionKeys
  commentId: T:FoundationaLLM.Common.Constants.Configuration.AuthorizationDependencyInjectionKeys
  href: FoundationaLLM.Common.Constants.Configuration.AuthorizationDependencyInjectionKeys.html
  name: AuthorizationDependencyInjectionKeys
  nameWithType: AuthorizationDependencyInjectionKeys
  fullName: FoundationaLLM.Common.Constants.Configuration.AuthorizationDependencyInjectionKeys
- uid: FoundationaLLM.Common.Constants.Configuration.AuthorizationKeyVaultSecretNames
  commentId: T:FoundationaLLM.Common.Constants.Configuration.AuthorizationKeyVaultSecretNames
  href: FoundationaLLM.Common.Constants.Configuration.AuthorizationKeyVaultSecretNames.html
  name: AuthorizationKeyVaultSecretNames
  nameWithType: AuthorizationKeyVaultSecretNames
  fullName: FoundationaLLM.Common.Constants.Configuration.AuthorizationKeyVaultSecretNames
- uid: FoundationaLLM.Common.Constants.Configuration.ConfigurationOptions
  commentId: T:FoundationaLLM.Common.Constants.Configuration.ConfigurationOptions
  href: FoundationaLLM.Common.Constants.Configuration.ConfigurationOptions.html
  name: ConfigurationOptions
  nameWithType: ConfigurationOptions
  fullName: FoundationaLLM.Common.Constants.Configuration.ConfigurationOptions
- uid: FoundationaLLM.Common.Constants.Configuration.DependencyInjectionKeys
  commentId: T:FoundationaLLM.Common.Constants.Configuration.DependencyInjectionKeys
  href: FoundationaLLM.Common.Constants.Configuration.DependencyInjectionKeys.html
  name: DependencyInjectionKeys
  nameWithType: DependencyInjectionKeys
  fullName: FoundationaLLM.Common.Constants.Configuration.DependencyInjectionKeys
- uid: FoundationaLLM.Common.Constants.Configuration.EnvironmentTypes
  commentId: T:FoundationaLLM.Common.Constants.Configuration.EnvironmentTypes
  href: FoundationaLLM.Common.Constants.Configuration.EnvironmentTypes.html
  name: EnvironmentTypes
  nameWithType: EnvironmentTypes
  fullName: FoundationaLLM.Common.Constants.Configuration.EnvironmentTypes
- uid: FoundationaLLM.Common.Constants.Configuration.EnvironmentVariables
  commentId: T:FoundationaLLM.Common.Constants.Configuration.EnvironmentVariables
  href: FoundationaLLM.Common.Constants.Configuration.EnvironmentVariables.html
  name: EnvironmentVariables
  nameWithType: EnvironmentVariables
  fullName: FoundationaLLM.Common.Constants.Configuration.EnvironmentVariables
- uid: FoundationaLLM.Common.Constants.Configuration.KeyVaultSecretNames
  commentId: T:FoundationaLLM.Common.Constants.Configuration.KeyVaultSecretNames
  href: FoundationaLLM.Common.Constants.Configuration.KeyVaultSecretNames.html
  name: KeyVaultSecretNames
  nameWithType: KeyVaultSecretNames
  fullName: FoundationaLLM.Common.Constants.Configuration.KeyVaultSecretNames
- uid: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames
  commentId: T:FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames
  href: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.html
  name: WellKnownAppConfigurationSetNames
  nameWithType: WellKnownAppConfigurationSetNames
  fullName: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames
- uid: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSets
  commentId: T:FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSets
  href: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSets.html
  name: WellKnownAppConfigurationSets
  nameWithType: WellKnownAppConfigurationSets
  fullName: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSets
