### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Models.Configuration.AppConfiguration
  commentId: N:FoundationaLLM.Common.Models.Configuration.AppConfiguration
  id: AppConfiguration
  parent: FoundationaLLM.Common.Models.Configuration
  children:
  - FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationEntry
  - FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationEventData
  - FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationKeyVaultUri
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.Models.Configuration.AppConfiguration
  nameWithType: FoundationaLLM.Common.Models.Configuration.AppConfiguration
  fullName: FoundationaLLM.Common.Models.Configuration.AppConfiguration
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationEntry
  commentId: T:FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationEntry
  href: FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationEntry.html
  name: AppConfigurationEntry
  nameWithType: AppConfigurationEntry
  fullName: FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationEntry
- uid: FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationEventData
  commentId: T:FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationEventData
  href: FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationEventData.html
  name: AppConfigurationEventData
  nameWithType: AppConfigurationEventData
  fullName: FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationEventData
- uid: FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationKeyVaultUri
  commentId: T:FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationKeyVaultUri
  href: FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationKeyVaultUri.html
  name: AppConfigurationKeyVaultUri
  nameWithType: AppConfigurationKeyVaultUri
  fullName: FoundationaLLM.Common.Models.Configuration.AppConfiguration.AppConfigurationKeyVaultUri
