### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Models.Configuration.Instance
  commentId: N:FoundationaLLM.Common.Models.Configuration.Instance
  id: Instance
  parent: FoundationaLLM.Common.Models.Configuration
  children:
  - FoundationaLLM.Common.Models.Configuration.Instance.InstanceSettings
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.Models.Configuration.Instance
  nameWithType: FoundationaLLM.Common.Models.Configuration.Instance
  fullName: FoundationaLLM.Common.Models.Configuration.Instance
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.Models.Configuration.Instance.InstanceSettings
  commentId: T:FoundationaLLM.Common.Models.Configuration.Instance.InstanceSettings
  parent: FoundationaLLM.Common.Models.Configuration.Instance
  href: FoundationaLLM.Common.Models.Configuration.Instance.InstanceSettings.html
  name: InstanceSettings
  nameWithType: InstanceSettings
  fullName: FoundationaLLM.Common.Models.Configuration.Instance.InstanceSettings
- uid: FoundationaLLM.Common.Models.Configuration.Instance
  commentId: N:FoundationaLLM.Common.Models.Configuration.Instance
  href: FoundationaLLM.html
  name: FoundationaLLM.Common.Models.Configuration.Instance
  nameWithType: FoundationaLLM.Common.Models.Configuration.Instance
  fullName: FoundationaLLM.Common.Models.Configuration.Instance
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Models
    name: Models
    href: FoundationaLLM.Common.Models.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration
    name: Configuration
    href: FoundationaLLM.Common.Models.Configuration.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration.Instance
    name: Instance
    href: FoundationaLLM.Common.Models.Configuration.Instance.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Models
    name: Models
    href: FoundationaLLM.Common.Models.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration
    name: Configuration
    href: FoundationaLLM.Common.Models.Configuration.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration.Instance
    name: Instance
    href: FoundationaLLM.Common.Models.Configuration.Instance.html
