### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Settings
  commentId: N:FoundationaLLM.Common.Settings
  id: Settings
  parent: FoundationaLLM.Common
  children:
  - FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions
  - FoundationaLLM.Common.Settings.CommonJsonSerializerOptions
  - FoundationaLLM.Common.Settings.CoreConfiguration
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.Settings
  nameWithType: FoundationaLLM.Common.Settings
  fullName: FoundationaLLM.Common.Settings
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions
  commentId: T:FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions
  href: FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions.html
  name: CommonHttpRetryStrategyOptions
  nameWithType: CommonHttpRetryStrategyOptions
  fullName: FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions
- uid: FoundationaLLM.Common.Settings.CommonJsonSerializerOptions
  commentId: T:FoundationaLLM.Common.Settings.CommonJsonSerializerOptions
  href: FoundationaLLM.Common.Settings.CommonJsonSerializerOptions.html
  name: CommonJsonSerializerOptions
  nameWithType: CommonJsonSerializerOptions
  fullName: FoundationaLLM.Common.Settings.CommonJsonSerializerOptions
- uid: FoundationaLLM.Common.Settings.CoreConfiguration
  commentId: T:FoundationaLLM.Common.Settings.CoreConfiguration
  href: FoundationaLLM.Common.Settings.CoreConfiguration.html
  name: CoreConfiguration
  nameWithType: CoreConfiguration
  fullName: FoundationaLLM.Common.Settings.CoreConfiguration
