### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Models.Configuration.Storage
  commentId: N:FoundationaLLM.Common.Models.Configuration.Storage
  id: Storage
  parent: FoundationaLLM.Common.Models.Configuration
  children:
  - FoundationaLLM.Common.Models.Configuration.Storage.BlobStorageServiceSettings
  - FoundationaLLM.Common.Models.Configuration.Storage.BlobStorageSettings
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.Models.Configuration.Storage
  nameWithType: FoundationaLLM.Common.Models.Configuration.Storage
  fullName: FoundationaLLM.Common.Models.Configuration.Storage
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.Models.Configuration.Storage.BlobStorageServiceSettings
  commentId: T:FoundationaLLM.Common.Models.Configuration.Storage.BlobStorageServiceSettings
  parent: FoundationaLLM.Common.Models.Configuration.Storage
  href: FoundationaLLM.Common.Models.Configuration.Storage.BlobStorageServiceSettings.html
  name: BlobStorageServiceSettings
  nameWithType: BlobStorageServiceSettings
  fullName: FoundationaLLM.Common.Models.Configuration.Storage.BlobStorageServiceSettings
- uid: FoundationaLLM.Common.Models.Configuration.Storage.BlobStorageSettings
  commentId: T:FoundationaLLM.Common.Models.Configuration.Storage.BlobStorageSettings
  href: FoundationaLLM.Common.Models.Configuration.Storage.BlobStorageSettings.html
  name: BlobStorageSettings
  nameWithType: BlobStorageSettings
  fullName: FoundationaLLM.Common.Models.Configuration.Storage.BlobStorageSettings
- uid: FoundationaLLM.Common.Models.Configuration.Storage
  commentId: N:FoundationaLLM.Common.Models.Configuration.Storage
  href: FoundationaLLM.html
  name: FoundationaLLM.Common.Models.Configuration.Storage
  nameWithType: FoundationaLLM.Common.Models.Configuration.Storage
  fullName: FoundationaLLM.Common.Models.Configuration.Storage
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Models
    name: Models
    href: FoundationaLLM.Common.Models.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration
    name: Configuration
    href: FoundationaLLM.Common.Models.Configuration.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration.Storage
    name: Storage
    href: FoundationaLLM.Common.Models.Configuration.Storage.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Models
    name: Models
    href: FoundationaLLM.Common.Models.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration
    name: Configuration
    href: FoundationaLLM.Common.Models.Configuration.html
  - name: .
  - uid: FoundationaLLM.Common.Models.Configuration.Storage
    name: Storage
    href: FoundationaLLM.Common.Models.Configuration.Storage.html
