### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions
  commentId: T:FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions
  id: CommonHttpRetryStrategyOptions
  parent: FoundationaLLM.Common.Settings
  children:
  - FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions.GetCommonHttpRetryStrategyOptions
  langs:
  - csharp
  - vb
  name: CommonHttpRetryStrategyOptions
  nameWithType: CommonHttpRetryStrategyOptions
  fullName: FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions
  type: Class
  source:
    remote:
      path: src/dotnet/Common/Settings/CommonHttpRetryStrategyOptions.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: CommonHttpRetryStrategyOptions
    path: ../src/dotnet/Common/Settings/CommonHttpRetryStrategyOptions.cs
    startLine: 9
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Settings
  summary: Common Http retry resiliency strategy options used by the API classes and their libraries.
  example: []
  syntax:
    content: public static class CommonHttpRetryStrategyOptions
    content.vb: Public Module CommonHttpRetryStrategyOptions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions.GetCommonHttpRetryStrategyOptions
  commentId: M:FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions.GetCommonHttpRetryStrategyOptions
  id: GetCommonHttpRetryStrategyOptions
  parent: FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions
  langs:
  - csharp
  - vb
  name: GetCommonHttpRetryStrategyOptions()
  nameWithType: CommonHttpRetryStrategyOptions.GetCommonHttpRetryStrategyOptions()
  fullName: FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions.GetCommonHttpRetryStrategyOptions()
  type: Method
  source:
    remote:
      path: src/dotnet/Common/Settings/CommonHttpRetryStrategyOptions.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: GetCommonHttpRetryStrategyOptions
    path: ../src/dotnet/Common/Settings/CommonHttpRetryStrategyOptions.cs
    startLine: 15
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Settings
  summary: Configures the commonly used Polly Http retry resiliency strategy options.
  example: []
  syntax:
    content: public static HttpRetryStrategyOptions GetCommonHttpRetryStrategyOptions()
    return:
      type: Microsoft.Extensions.Http.Resilience.HttpRetryStrategyOptions
      description: ''
    content.vb: Public Shared Function GetCommonHttpRetryStrategyOptions() As HttpRetryStrategyOptions
  overload: FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions.GetCommonHttpRetryStrategyOptions*
references:
- uid: FoundationaLLM.Common.Settings
  commentId: N:FoundationaLLM.Common.Settings
  href: FoundationaLLM.html
  name: FoundationaLLM.Common.Settings
  nameWithType: FoundationaLLM.Common.Settings
  fullName: FoundationaLLM.Common.Settings
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Settings
    name: Settings
    href: FoundationaLLM.Common.Settings.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Settings
    name: Settings
    href: FoundationaLLM.Common.Settings.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions.GetCommonHttpRetryStrategyOptions*
  commentId: Overload:FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions.GetCommonHttpRetryStrategyOptions
  href: FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions.html#FoundationaLLM_Common_Settings_CommonHttpRetryStrategyOptions_GetCommonHttpRetryStrategyOptions
  name: GetCommonHttpRetryStrategyOptions
  nameWithType: CommonHttpRetryStrategyOptions.GetCommonHttpRetryStrategyOptions
  fullName: FoundationaLLM.Common.Settings.CommonHttpRetryStrategyOptions.GetCommonHttpRetryStrategyOptions
- uid: Microsoft.Extensions.Http.Resilience.HttpRetryStrategyOptions
  commentId: T:Microsoft.Extensions.Http.Resilience.HttpRetryStrategyOptions
  parent: Microsoft.Extensions.Http.Resilience
  isExternal: true
  name: HttpRetryStrategyOptions
  nameWithType: HttpRetryStrategyOptions
  fullName: Microsoft.Extensions.Http.Resilience.HttpRetryStrategyOptions
- uid: Microsoft.Extensions.Http.Resilience
  commentId: N:Microsoft.Extensions.Http.Resilience
  isExternal: true
  name: Microsoft.Extensions.Http.Resilience
  nameWithType: Microsoft.Extensions.Http.Resilience
  fullName: Microsoft.Extensions.Http.Resilience
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions.Http
    name: Http
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions.Http.Resilience
    name: Resilience
    isExternal: true
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions
    name: Extensions
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions.Http
    name: Http
    isExternal: true
  - name: .
  - uid: Microsoft.Extensions.Http.Resilience
    name: Resilience
    isExternal: true
