### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames
  commentId: T:FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames
  id: WellKnownAppConfigurationSetNames
  parent: FoundationaLLM.Common.Constants.Configuration
  children:
  - FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.All
  - FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.ManagementPortal
  - FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.UserPortal
  langs:
  - csharp
  - vb
  name: WellKnownAppConfigurationSetNames
  nameWithType: WellKnownAppConfigurationSetNames
  fullName: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames
  type: Class
  source:
    remote:
      path: src/dotnet/Common/Constants/Configuration/WellKnownAppConfigurationSetNames.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: WellKnownAppConfigurationSetNames
    path: ../src/dotnet/Common/Constants/Configuration/WellKnownAppConfigurationSetNames.cs
    startLine: 5
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Constants.Configuration
  summary: Provides a collection of well-known names for application configuration sets.
  example: []
  syntax:
    content: public static class WellKnownAppConfigurationSetNames
    content.vb: Public Module WellKnownAppConfigurationSetNames
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.UserPortal
  commentId: F:FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.UserPortal
  id: UserPortal
  parent: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames
  langs:
  - csharp
  - vb
  name: UserPortal
  nameWithType: WellKnownAppConfigurationSetNames.UserPortal
  fullName: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.UserPortal
  type: Field
  source:
    remote:
      path: src/dotnet/Common/Constants/Configuration/WellKnownAppConfigurationSetNames.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: UserPortal
    path: ../src/dotnet/Common/Constants/Configuration/WellKnownAppConfigurationSetNames.cs
    startLine: 10
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Constants.Configuration
  summary: The application configuration set used by the user portal.
  example: []
  syntax:
    content: public const string UserPortal = "UserPortal"
    return:
      type: System.String
    content.vb: Public Const UserPortal As String = "UserPortal"
- uid: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.ManagementPortal
  commentId: F:FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.ManagementPortal
  id: ManagementPortal
  parent: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames
  langs:
  - csharp
  - vb
  name: ManagementPortal
  nameWithType: WellKnownAppConfigurationSetNames.ManagementPortal
  fullName: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.ManagementPortal
  type: Field
  source:
    remote:
      path: src/dotnet/Common/Constants/Configuration/WellKnownAppConfigurationSetNames.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: ManagementPortal
    path: ../src/dotnet/Common/Constants/Configuration/WellKnownAppConfigurationSetNames.cs
    startLine: 15
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Constants.Configuration
  summary: The application configuration set used by the management portal.
  example: []
  syntax:
    content: public const string ManagementPortal = "ManagementPortal"
    return:
      type: System.String
    content.vb: Public Const ManagementPortal As String = "ManagementPortal"
- uid: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.All
  commentId: F:FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.All
  id: All
  parent: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames
  langs:
  - csharp
  - vb
  name: All
  nameWithType: WellKnownAppConfigurationSetNames.All
  fullName: FoundationaLLM.Common.Constants.Configuration.WellKnownAppConfigurationSetNames.All
  type: Field
  source:
    remote:
      path: src/dotnet/Common/Constants/Configuration/WellKnownAppConfigurationSetNames.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: All
    path: ../src/dotnet/Common/Constants/Configuration/WellKnownAppConfigurationSetNames.cs
    startLine: 20
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Constants.Configuration
  summary: All application configuration sets.
  example: []
  syntax:
    content: public static readonly string[] All
    return:
      type: System.String[]
    content.vb: Public Shared ReadOnly All As String()
references:
- uid: FoundationaLLM.Common.Constants.Configuration
  commentId: N:FoundationaLLM.Common.Constants.Configuration
  href: FoundationaLLM.html
  name: FoundationaLLM.Common.Constants.Configuration
  nameWithType: FoundationaLLM.Common.Constants.Configuration
  fullName: FoundationaLLM.Common.Constants.Configuration
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Constants
    name: Constants
    href: FoundationaLLM.Common.Constants.html
  - name: .
  - uid: FoundationaLLM.Common.Constants.Configuration
    name: Configuration
    href: FoundationaLLM.Common.Constants.Configuration.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Constants
    name: Constants
    href: FoundationaLLM.Common.Constants.html
  - name: .
  - uid: FoundationaLLM.Common.Constants.Configuration
    name: Configuration
    href: FoundationaLLM.Common.Constants.Configuration.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.String[]
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string[]
  nameWithType: string[]
  fullName: string[]
  nameWithType.vb: String()
  fullName.vb: String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '['
  - name: ']'
  spec.vb:
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: (
  - name: )
