### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Configuration.Catalog
  commentId: N:FoundationaLLM.Configuration.Catalog
  id: Catalog
  parent: FoundationaLLM.Configuration
  children:
  - FoundationaLLM.Configuration.Catalog.AppConfigurationCatalog
  - FoundationaLLM.Configuration.Catalog.EnvironmentVariablesCatalog
  - FoundationaLLM.Configuration.Catalog.KeyVaultSecretsCatalog
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Configuration.Catalog
  nameWithType: FoundationaLLM.Configuration.Catalog
  fullName: FoundationaLLM.Configuration.Catalog
  type: Namespace
  assemblies:
  - FoundationaLLM.Configuration
references:
- uid: FoundationaLLM.Configuration.Catalog.AppConfigurationCatalog
  commentId: T:FoundationaLLM.Configuration.Catalog.AppConfigurationCatalog
  href: FoundationaLLM.Configuration.Catalog.AppConfigurationCatalog.html
  name: AppConfigurationCatalog
  nameWithType: AppConfigurationCatalog
  fullName: FoundationaLLM.Configuration.Catalog.AppConfigurationCatalog
- uid: FoundationaLLM.Configuration.Catalog.EnvironmentVariablesCatalog
  commentId: T:FoundationaLLM.Configuration.Catalog.EnvironmentVariablesCatalog
  href: FoundationaLLM.Configuration.Catalog.EnvironmentVariablesCatalog.html
  name: EnvironmentVariablesCatalog
  nameWithType: EnvironmentVariablesCatalog
  fullName: FoundationaLLM.Configuration.Catalog.EnvironmentVariablesCatalog
- uid: FoundationaLLM.Configuration.Catalog.KeyVaultSecretsCatalog
  commentId: T:FoundationaLLM.Configuration.Catalog.KeyVaultSecretsCatalog
  href: FoundationaLLM.Configuration.Catalog.KeyVaultSecretsCatalog.html
  name: KeyVaultSecretsCatalog
  nameWithType: KeyVaultSecretsCatalog
  fullName: FoundationaLLM.Configuration.Catalog.KeyVaultSecretsCatalog
