### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys
  commentId: T:FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys
  id: DataSourceConfigurationReferenceKeys
  parent: FoundationaLLM.Common.Constants.DataSource
  children:
  - FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.CertificateName
  - FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.ClientId
  - FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.KeyVaultUrl
  - FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.TenantId
  langs:
  - csharp
  - vb
  name: DataSourceConfigurationReferenceKeys
  nameWithType: DataSourceConfigurationReferenceKeys
  fullName: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys
  type: Class
  source:
    remote:
      path: src/dotnet/Common/Constants/DataSource/DataSourceConfigurationReferenceKeys.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: DataSourceConfigurationReferenceKeys
    path: ../src/dotnet/Common/Constants/DataSource/DataSourceConfigurationReferenceKeys.cs
    startLine: 5
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Constants.DataSource
  summary: Defines the keys for data source configuration references.
  example: []
  syntax:
    content: public static class DataSourceConfigurationReferenceKeys
    content.vb: Public Module DataSourceConfigurationReferenceKeys
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.ClientId
  commentId: F:FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.ClientId
  id: ClientId
  parent: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys
  langs:
  - csharp
  - vb
  name: ClientId
  nameWithType: DataSourceConfigurationReferenceKeys.ClientId
  fullName: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.ClientId
  type: Field
  source:
    remote:
      path: src/dotnet/Common/Constants/DataSource/DataSourceConfigurationReferenceKeys.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: ClientId
    path: ../src/dotnet/Common/Constants/DataSource/DataSourceConfigurationReferenceKeys.cs
    startLine: 10
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Constants.DataSource
  summary: The client identifier of the application registration.
  example: []
  syntax:
    content: public const string ClientId = "ClientId"
    return:
      type: System.String
    content.vb: Public Const ClientId As String = "ClientId"
- uid: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.TenantId
  commentId: F:FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.TenantId
  id: TenantId
  parent: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys
  langs:
  - csharp
  - vb
  name: TenantId
  nameWithType: DataSourceConfigurationReferenceKeys.TenantId
  fullName: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.TenantId
  type: Field
  source:
    remote:
      path: src/dotnet/Common/Constants/DataSource/DataSourceConfigurationReferenceKeys.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: TenantId
    path: ../src/dotnet/Common/Constants/DataSource/DataSourceConfigurationReferenceKeys.cs
    startLine: 15
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Constants.DataSource
  summary: The Entra ID tenant identifier where the application registration is located.
  example: []
  syntax:
    content: public const string TenantId = "TenantId"
    return:
      type: System.String
    content.vb: Public Const TenantId As String = "TenantId"
- uid: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.CertificateName
  commentId: F:FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.CertificateName
  id: CertificateName
  parent: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys
  langs:
  - csharp
  - vb
  name: CertificateName
  nameWithType: DataSourceConfigurationReferenceKeys.CertificateName
  fullName: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.CertificateName
  type: Field
  source:
    remote:
      path: src/dotnet/Common/Constants/DataSource/DataSourceConfigurationReferenceKeys.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: CertificateName
    path: ../src/dotnet/Common/Constants/DataSource/DataSourceConfigurationReferenceKeys.cs
    startLine: 20
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Constants.DataSource
  summary: The name of the X.509 certificate used for authentication.
  example: []
  syntax:
    content: public const string CertificateName = "CertificateName"
    return:
      type: System.String
    content.vb: Public Const CertificateName As String = "CertificateName"
- uid: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.KeyVaultUrl
  commentId: F:FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.KeyVaultUrl
  id: KeyVaultUrl
  parent: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys
  langs:
  - csharp
  - vb
  name: KeyVaultUrl
  nameWithType: DataSourceConfigurationReferenceKeys.KeyVaultUrl
  fullName: FoundationaLLM.Common.Constants.DataSource.DataSourceConfigurationReferenceKeys.KeyVaultUrl
  type: Field
  source:
    remote:
      path: src/dotnet/Common/Constants/DataSource/DataSourceConfigurationReferenceKeys.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: KeyVaultUrl
    path: ../src/dotnet/Common/Constants/DataSource/DataSourceConfigurationReferenceKeys.cs
    startLine: 25
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Constants.DataSource
  summary: The URL of the Azure Key Vault where the X.509 certificate is stored.
  example: []
  syntax:
    content: public const string KeyVaultUrl = "KeyVaultURL"
    return:
      type: System.String
    content.vb: Public Const KeyVaultUrl As String = "KeyVaultURL"
references:
- uid: FoundationaLLM.Common.Constants.DataSource
  commentId: N:FoundationaLLM.Common.Constants.DataSource
  href: FoundationaLLM.html
  name: FoundationaLLM.Common.Constants.DataSource
  nameWithType: FoundationaLLM.Common.Constants.DataSource
  fullName: FoundationaLLM.Common.Constants.DataSource
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Constants
    name: Constants
    href: FoundationaLLM.Common.Constants.html
  - name: .
  - uid: FoundationaLLM.Common.Constants.DataSource
    name: DataSource
    href: FoundationaLLM.Common.Constants.DataSource.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Constants
    name: Constants
    href: FoundationaLLM.Common.Constants.html
  - name: .
  - uid: FoundationaLLM.Common.Constants.DataSource
    name: DataSource
    href: FoundationaLLM.Common.Constants.DataSource.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
