### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Configuration
  id: Configuration
  parent: FoundationaLLM
  children:
  - FoundationaLLM.Configuration.Catalog
  - FoundationaLLM.Configuration.Interfaces
  - FoundationaLLM.Configuration.Models
  - FoundationaLLM.Configuration.Services
  - FoundationaLLM.Configuration.Validation
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Configuration
  type: Namespace
references:
- uid: FoundationaLLM.Configuration.Catalog
  commentId: N:FoundationaLLM.Configuration.Catalog
  href: FoundationaLLM.html
  name: FoundationaLLM.Configuration.Catalog
  nameWithType: FoundationaLLM.Configuration.Catalog
  fullName: FoundationaLLM.Configuration.Catalog
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Configuration
    name: Configuration
    href: FoundationaLLM.Configuration.html
  - name: .
  - uid: FoundationaLLM.Configuration.Catalog
    name: Catalog
    href: FoundationaLLM.Configuration.Catalog.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Configuration
    name: Configuration
    href: FoundationaLLM.Configuration.html
  - name: .
  - uid: FoundationaLLM.Configuration.Catalog
    name: Catalog
    href: FoundationaLLM.Configuration.Catalog.html
- uid: FoundationaLLM.Configuration.Interfaces
  commentId: N:FoundationaLLM.Configuration.Interfaces
  href: FoundationaLLM.html
  name: FoundationaLLM.Configuration.Interfaces
  nameWithType: FoundationaLLM.Configuration.Interfaces
  fullName: FoundationaLLM.Configuration.Interfaces
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Configuration
    name: Configuration
    href: FoundationaLLM.Configuration.html
  - name: .
  - uid: FoundationaLLM.Configuration.Interfaces
    name: Interfaces
    href: FoundationaLLM.Configuration.Interfaces.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Configuration
    name: Configuration
    href: FoundationaLLM.Configuration.html
  - name: .
  - uid: FoundationaLLM.Configuration.Interfaces
    name: Interfaces
    href: FoundationaLLM.Configuration.Interfaces.html
- uid: FoundationaLLM.Configuration.Models
  commentId: N:FoundationaLLM.Configuration.Models
  href: FoundationaLLM.html
  name: FoundationaLLM.Configuration.Models
  nameWithType: FoundationaLLM.Configuration.Models
  fullName: FoundationaLLM.Configuration.Models
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Configuration
    name: Configuration
    href: FoundationaLLM.Configuration.html
  - name: .
  - uid: FoundationaLLM.Configuration.Models
    name: Models
    href: FoundationaLLM.Configuration.Models.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Configuration
    name: Configuration
    href: FoundationaLLM.Configuration.html
  - name: .
  - uid: FoundationaLLM.Configuration.Models
    name: Models
    href: FoundationaLLM.Configuration.Models.html
- uid: FoundationaLLM.Configuration.Services
  commentId: N:FoundationaLLM.Configuration.Services
  href: FoundationaLLM.html
  name: FoundationaLLM.Configuration.Services
  nameWithType: FoundationaLLM.Configuration.Services
  fullName: FoundationaLLM.Configuration.Services
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Configuration
    name: Configuration
    href: FoundationaLLM.Configuration.html
  - name: .
  - uid: FoundationaLLM.Configuration.Services
    name: Services
    href: FoundationaLLM.Configuration.Services.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Configuration
    name: Configuration
    href: FoundationaLLM.Configuration.html
  - name: .
  - uid: FoundationaLLM.Configuration.Services
    name: Services
    href: FoundationaLLM.Configuration.Services.html
- uid: FoundationaLLM.Configuration.Validation
  commentId: N:FoundationaLLM.Configuration.Validation
  href: FoundationaLLM.html
  name: FoundationaLLM.Configuration.Validation
  nameWithType: FoundationaLLM.Configuration.Validation
  fullName: FoundationaLLM.Configuration.Validation
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Configuration
    name: Configuration
    href: FoundationaLLM.Configuration.html
  - name: .
  - uid: FoundationaLLM.Configuration.Validation
    name: Validation
    href: FoundationaLLM.Configuration.Validation.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Configuration
    name: Configuration
    href: FoundationaLLM.Configuration.html
  - name: .
  - uid: FoundationaLLM.Configuration.Validation
    name: Validation
    href: FoundationaLLM.Configuration.Validation.html
