### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.AuthorizationEngine.Models.Configuration
  commentId: N:FoundationaLLM.AuthorizationEngine.Models.Configuration
  id: Configuration
  parent: FoundationaLLM.AuthorizationEngine.Models
  children:
  - FoundationaLLM.AuthorizationEngine.Models.Configuration.AuthorizationCoreSettings
  langs:
  - csharp
  - vb
  name: FoundationaLLM.AuthorizationEngine.Models.Configuration
  nameWithType: FoundationaLLM.AuthorizationEngine.Models.Configuration
  fullName: FoundationaLLM.AuthorizationEngine.Models.Configuration
  type: Namespace
  assemblies:
  - FoundationaLLM.AuthorizationEngine
references:
- uid: FoundationaLLM.AuthorizationEngine.Models.Configuration.AuthorizationCoreSettings
  commentId: T:FoundationaLLM.AuthorizationEngine.Models.Configuration.AuthorizationCoreSettings
  href: FoundationaLLM.AuthorizationEngine.Models.Configuration.AuthorizationCoreSettings.html
  name: AuthorizationCoreSettings
  nameWithType: AuthorizationCoreSettings
  fullName: FoundationaLLM.AuthorizationEngine.Models.Configuration.AuthorizationCoreSettings
