### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.State.Models.Configuration
  commentId: N:FoundationaLLM.State.Models.Configuration
  id: Models.Configuration
  parent: FoundationaLLM.State
  children:
  - FoundationaLLM.State.Models.Configuration.StateServiceSettings
  langs:
  - csharp
  - vb
  name: FoundationaLLM.State.Models.Configuration
  nameWithType: FoundationaLLM.State.Models.Configuration
  fullName: FoundationaLLM.State.Models.Configuration
  type: Namespace
  assemblies:
  - FoundationaLLM.State
references:
- uid: FoundationaLLM.State.Models.Configuration.StateServiceSettings
  commentId: T:FoundationaLLM.State.Models.Configuration.StateServiceSettings
  href: FoundationaLLM.State.Models.Configuration.StateServiceSettings.html
  name: StateServiceSettings
  nameWithType: StateServiceSettings
  fullName: FoundationaLLM.State.Models.Configuration.StateServiceSettings
