### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Models.Configuration.Branding
  commentId: N:FoundationaLLM.Common.Models.Configuration.Branding
  id: Branding
  parent: FoundationaLLM.Common.Models.Configuration
  children:
  - FoundationaLLM.Common.Models.Configuration.Branding.ClientBrandingConfiguration
  langs:
  - csharp
  - vb
  name: FoundationaLLM.Common.Models.Configuration.Branding
  nameWithType: FoundationaLLM.Common.Models.Configuration.Branding
  fullName: FoundationaLLM.Common.Models.Configuration.Branding
  type: Namespace
  assemblies:
  - FoundationaLLM.Common
references:
- uid: FoundationaLLM.Common.Models.Configuration.Branding.ClientBrandingConfiguration
  commentId: T:FoundationaLLM.Common.Models.Configuration.Branding.ClientBrandingConfiguration
  href: FoundationaLLM.Common.Models.Configuration.Branding.ClientBrandingConfiguration.html
  name: ClientBrandingConfiguration
  nameWithType: ClientBrandingConfiguration
  fullName: FoundationaLLM.Common.Models.Configuration.Branding.ClientBrandingConfiguration
