### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions
  commentId: T:FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions
  id: SwaggerGenOptionsExtensions
  parent: FoundationaLLM.Common.Extensions
  children:
  - FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions.AddAPIKeyAuth(Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions)
  langs:
  - csharp
  - vb
  name: SwaggerGenOptionsExtensions
  nameWithType: SwaggerGenOptionsExtensions
  fullName: FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions
  type: Class
  source:
    remote:
      path: src/dotnet/Common/Extensions/SwaggerGenOptionsExtensions.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: SwaggerGenOptionsExtensions
    path: ../src/dotnet/Common/Extensions/SwaggerGenOptionsExtensions.cs
    startLine: 10
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Extensions
  summary: Extends the SwaggerGenOptions with common options used by the FoundationaLLM APIs.
  example: []
  syntax:
    content: public static class SwaggerGenOptionsExtensions
    content.vb: Public Module SwaggerGenOptionsExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions.AddAPIKeyAuth(Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions)
  commentId: M:FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions.AddAPIKeyAuth(Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions)
  id: AddAPIKeyAuth(Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions)
  isExtensionMethod: true
  parent: FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions
  langs:
  - csharp
  - vb
  name: AddAPIKeyAuth(SwaggerGenOptions)
  nameWithType: SwaggerGenOptionsExtensions.AddAPIKeyAuth(SwaggerGenOptions)
  fullName: FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions.AddAPIKeyAuth(Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions)
  type: Method
  source:
    remote:
      path: src/dotnet/Common/Extensions/SwaggerGenOptionsExtensions.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: AddAPIKeyAuth
    path: ../src/dotnet/Common/Extensions/SwaggerGenOptionsExtensions.cs
    startLine: 16
  assemblies:
  - FoundationaLLM.Common
  namespace: FoundationaLLM.Common.Extensions
  summary: Extension method that configures API Key auth for the APIs that use it.
  example: []
  syntax:
    content: public static void AddAPIKeyAuth(this SwaggerGenOptions options)
    parameters:
    - id: options
      type: Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions
      description: The base options.
    content.vb: Public Shared Sub AddAPIKeyAuth(options As SwaggerGenOptions)
  overload: FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions.AddAPIKeyAuth*
references:
- uid: FoundationaLLM.Common.Extensions
  commentId: N:FoundationaLLM.Common.Extensions
  href: FoundationaLLM.html
  name: FoundationaLLM.Common.Extensions
  nameWithType: FoundationaLLM.Common.Extensions
  fullName: FoundationaLLM.Common.Extensions
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Extensions
    name: Extensions
    href: FoundationaLLM.Common.Extensions.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Common
    name: Common
    href: FoundationaLLM.Common.html
  - name: .
  - uid: FoundationaLLM.Common.Extensions
    name: Extensions
    href: FoundationaLLM.Common.Extensions.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions.AddAPIKeyAuth*
  commentId: Overload:FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions.AddAPIKeyAuth
  href: FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions.html#FoundationaLLM_Common_Extensions_SwaggerGenOptionsExtensions_AddAPIKeyAuth_Swashbuckle_AspNetCore_SwaggerGen_SwaggerGenOptions_
  name: AddAPIKeyAuth
  nameWithType: SwaggerGenOptionsExtensions.AddAPIKeyAuth
  fullName: FoundationaLLM.Common.Extensions.SwaggerGenOptionsExtensions.AddAPIKeyAuth
- uid: Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions
  commentId: T:Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions
  parent: Swashbuckle.AspNetCore.SwaggerGen
  isExternal: true
  href: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenOptions.cs
  name: SwaggerGenOptions
  nameWithType: SwaggerGenOptions
  fullName: Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenOptions
- uid: Swashbuckle.AspNetCore.SwaggerGen
  commentId: N:Swashbuckle.AspNetCore.SwaggerGen
  isExternal: true
  name: Swashbuckle.AspNetCore.SwaggerGen
  nameWithType: Swashbuckle.AspNetCore.SwaggerGen
  fullName: Swashbuckle.AspNetCore.SwaggerGen
  spec.csharp:
  - uid: Swashbuckle
    name: Swashbuckle
    isExternal: true
  - name: .
  - uid: Swashbuckle.AspNetCore
    name: AspNetCore
    isExternal: true
  - name: .
  - uid: Swashbuckle.AspNetCore.SwaggerGen
    name: SwaggerGen
    isExternal: true
  spec.vb:
  - uid: Swashbuckle
    name: Swashbuckle
    isExternal: true
  - name: .
  - uid: Swashbuckle.AspNetCore
    name: AspNetCore
    isExternal: true
  - name: .
  - uid: Swashbuckle.AspNetCore.SwaggerGen
    name: SwaggerGen
    isExternal: true
