### YamlMime:ManagedReference
items:
- uid: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks
  commentId: T:FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks
  id: IConfigurationHealthChecks
  parent: FoundationaLLM.Configuration.Interfaces
  children:
  - FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateConfigurationsAsync(System.String)
  - FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateEnvironmentVariables
  - FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateKeyVaultSecretsAsync(System.String)
  langs:
  - csharp
  - vb
  name: IConfigurationHealthChecks
  nameWithType: IConfigurationHealthChecks
  fullName: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks
  type: Interface
  source:
    remote:
      path: src/dotnet/Configuration/Interfaces/IConfigurationHealthChecks.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: IConfigurationHealthChecks
    path: ../src/dotnet/Configuration/Interfaces/IConfigurationHealthChecks.cs
    startLine: 7
  assemblies:
  - FoundationaLLM.Configuration
  namespace: FoundationaLLM.Configuration.Interfaces
  summary: Provides health checks for the application's configuration settings.
  example: []
  syntax:
    content: public interface IConfigurationHealthChecks
    content.vb: Public Interface IConfigurationHealthChecks
  extensionMethods:
  - System.Object.FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(System.Collections.Generic.List{System.String})
- uid: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateConfigurationsAsync(System.String)
  commentId: M:FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateConfigurationsAsync(System.String)
  id: ValidateConfigurationsAsync(System.String)
  parent: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks
  langs:
  - csharp
  - vb
  name: ValidateConfigurationsAsync(string)
  nameWithType: IConfigurationHealthChecks.ValidateConfigurationsAsync(string)
  fullName: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateConfigurationsAsync(string)
  type: Method
  source:
    remote:
      path: src/dotnet/Configuration/Interfaces/IConfigurationHealthChecks.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: ValidateConfigurationsAsync
    path: ../src/dotnet/Configuration/Interfaces/IConfigurationHealthChecks.cs
    startLine: 14
  assemblies:
  - FoundationaLLM.Configuration
  namespace: FoundationaLLM.Configuration.Interfaces
  summary: Validates the application's configuration settings.
  example: []
  syntax:
    content: Task ValidateConfigurationsAsync(string version)
    parameters:
    - id: version
      type: System.String
      description: The current app version.
    return:
      type: System.Threading.Tasks.Task
      description: ''
    content.vb: Function ValidateConfigurationsAsync(version As String) As Task
  overload: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateConfigurationsAsync*
  nameWithType.vb: IConfigurationHealthChecks.ValidateConfigurationsAsync(String)
  fullName.vb: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateConfigurationsAsync(String)
  name.vb: ValidateConfigurationsAsync(String)
- uid: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateKeyVaultSecretsAsync(System.String)
  commentId: M:FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateKeyVaultSecretsAsync(System.String)
  id: ValidateKeyVaultSecretsAsync(System.String)
  parent: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks
  langs:
  - csharp
  - vb
  name: ValidateKeyVaultSecretsAsync(string)
  nameWithType: IConfigurationHealthChecks.ValidateKeyVaultSecretsAsync(string)
  fullName: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateKeyVaultSecretsAsync(string)
  type: Method
  source:
    remote:
      path: src/dotnet/Configuration/Interfaces/IConfigurationHealthChecks.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: ValidateKeyVaultSecretsAsync
    path: ../src/dotnet/Configuration/Interfaces/IConfigurationHealthChecks.cs
    startLine: 22
  assemblies:
  - FoundationaLLM.Configuration
  namespace: FoundationaLLM.Configuration.Interfaces
  summary: Validates the application's Key Vault secrets.
  example: []
  syntax:
    content: Task ValidateKeyVaultSecretsAsync(string version)
    parameters:
    - id: version
      type: System.String
      description: The current app version.
    return:
      type: System.Threading.Tasks.Task
      description: ''
    content.vb: Function ValidateKeyVaultSecretsAsync(version As String) As Task
  overload: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateKeyVaultSecretsAsync*
  exceptions:
  - type: FoundationaLLM.Common.Exceptions.ConfigurationValidationException
    commentId: T:FoundationaLLM.Common.Exceptions.ConfigurationValidationException
    description: ''
  nameWithType.vb: IConfigurationHealthChecks.ValidateKeyVaultSecretsAsync(String)
  fullName.vb: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateKeyVaultSecretsAsync(String)
  name.vb: ValidateKeyVaultSecretsAsync(String)
- uid: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateEnvironmentVariables
  commentId: M:FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateEnvironmentVariables
  id: ValidateEnvironmentVariables
  parent: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks
  langs:
  - csharp
  - vb
  name: ValidateEnvironmentVariables()
  nameWithType: IConfigurationHealthChecks.ValidateEnvironmentVariables()
  fullName: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateEnvironmentVariables()
  type: Method
  source:
    remote:
      path: src/dotnet/Configuration/Interfaces/IConfigurationHealthChecks.cs
      branch: cursor/documentation-navigation-fix-f293
      repo: https://github.com/foundationallm/foundationallm.git
    id: ValidateEnvironmentVariables
    path: ../src/dotnet/Configuration/Interfaces/IConfigurationHealthChecks.cs
    startLine: 27
  assemblies:
  - FoundationaLLM.Configuration
  namespace: FoundationaLLM.Configuration.Interfaces
  summary: Validates the application's environment variables.
  example: []
  syntax:
    content: void ValidateEnvironmentVariables()
    content.vb: Sub ValidateEnvironmentVariables()
  overload: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateEnvironmentVariables*
references:
- uid: FoundationaLLM.Configuration.Interfaces
  commentId: N:FoundationaLLM.Configuration.Interfaces
  href: FoundationaLLM.html
  name: FoundationaLLM.Configuration.Interfaces
  nameWithType: FoundationaLLM.Configuration.Interfaces
  fullName: FoundationaLLM.Configuration.Interfaces
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Configuration
    name: Configuration
    href: FoundationaLLM.Configuration.html
  - name: .
  - uid: FoundationaLLM.Configuration.Interfaces
    name: Interfaces
    href: FoundationaLLM.Configuration.Interfaces.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Configuration
    name: Configuration
    href: FoundationaLLM.Configuration.html
  - name: .
  - uid: FoundationaLLM.Configuration.Interfaces
    name: Interfaces
    href: FoundationaLLM.Configuration.Interfaces.html
- uid: System.Object.FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(System.Collections.Generic.List{System.String})
  commentId: M:FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(System.Object,System.Collections.Generic.List{System.String})
  parent: FoundationaLLM.Core.Utils.ObjectExtensions
  definition: FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(System.Object,System.Collections.Generic.List{System.String})
  href: FoundationaLLM.Core.Utils.ObjectExtensions.html#FoundationaLLM_Core_Utils_ObjectExtensions_GetPropertyValues_System_Object_System_Collections_Generic_List_System_String__
  name: GetPropertyValues(object, List<string>)
  nameWithType: ObjectExtensions.GetPropertyValues(object, List<string>)
  fullName: FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(object, System.Collections.Generic.List<string>)
  nameWithType.vb: ObjectExtensions.GetPropertyValues(Object, List(Of String))
  fullName.vb: FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(Object, System.Collections.Generic.List(Of String))
  name.vb: GetPropertyValues(Object, List(Of String))
  spec.csharp:
  - uid: FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(System.Object,System.Collections.Generic.List{System.String})
    name: GetPropertyValues
    href: FoundationaLLM.Core.Utils.ObjectExtensions.html#FoundationaLLM_Core_Utils_ObjectExtensions_GetPropertyValues_System_Object_System_Collections_Generic_List_System_String__
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  - name: )
  spec.vb:
  - uid: FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(System.Object,System.Collections.Generic.List{System.String})
    name: GetPropertyValues
    href: FoundationaLLM.Core.Utils.ObjectExtensions.html#FoundationaLLM_Core_Utils_ObjectExtensions_GetPropertyValues_System_Object_System_Collections_Generic_List_System_String__
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  - name: )
- uid: FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(System.Object,System.Collections.Generic.List{System.String})
  commentId: M:FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(System.Object,System.Collections.Generic.List{System.String})
  isExternal: true
  href: FoundationaLLM.Core.Utils.ObjectExtensions.html#FoundationaLLM_Core_Utils_ObjectExtensions_GetPropertyValues_System_Object_System_Collections_Generic_List_System_String__
  name: GetPropertyValues(object, List<string>)
  nameWithType: ObjectExtensions.GetPropertyValues(object, List<string>)
  fullName: FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(object, System.Collections.Generic.List<string>)
  nameWithType.vb: ObjectExtensions.GetPropertyValues(Object, List(Of String))
  fullName.vb: FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(Object, System.Collections.Generic.List(Of String))
  name.vb: GetPropertyValues(Object, List(Of String))
  spec.csharp:
  - uid: FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(System.Object,System.Collections.Generic.List{System.String})
    name: GetPropertyValues
    href: FoundationaLLM.Core.Utils.ObjectExtensions.html#FoundationaLLM_Core_Utils_ObjectExtensions_GetPropertyValues_System_Object_System_Collections_Generic_List_System_String__
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  - name: )
  spec.vb:
  - uid: FoundationaLLM.Core.Utils.ObjectExtensions.GetPropertyValues(System.Object,System.Collections.Generic.List{System.String})
    name: GetPropertyValues
    href: FoundationaLLM.Core.Utils.ObjectExtensions.html#FoundationaLLM_Core_Utils_ObjectExtensions_GetPropertyValues_System_Object_System_Collections_Generic_List_System_String__
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Collections.Generic.List`1
    name: List
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.generic.list-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
  - name: )
- uid: FoundationaLLM.Core.Utils.ObjectExtensions
  commentId: T:FoundationaLLM.Core.Utils.ObjectExtensions
  parent: FoundationaLLM.Core.Utils
  href: FoundationaLLM.Core.Utils.ObjectExtensions.html
  name: ObjectExtensions
  nameWithType: ObjectExtensions
  fullName: FoundationaLLM.Core.Utils.ObjectExtensions
- uid: FoundationaLLM.Core.Utils
  commentId: N:FoundationaLLM.Core.Utils
  href: FoundationaLLM.html
  name: FoundationaLLM.Core.Utils
  nameWithType: FoundationaLLM.Core.Utils
  fullName: FoundationaLLM.Core.Utils
  spec.csharp:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Core
    name: Core
    href: FoundationaLLM.Core.html
  - name: .
  - uid: FoundationaLLM.Core.Utils
    name: Utils
    href: FoundationaLLM.Core.Utils.html
  spec.vb:
  - uid: FoundationaLLM
    name: FoundationaLLM
    href: FoundationaLLM.html
  - name: .
  - uid: FoundationaLLM.Core
    name: Core
    href: FoundationaLLM.Core.html
  - name: .
  - uid: FoundationaLLM.Core.Utils
    name: Utils
    href: FoundationaLLM.Core.Utils.html
- uid: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateConfigurationsAsync*
  commentId: Overload:FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateConfigurationsAsync
  href: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.html#FoundationaLLM_Configuration_Interfaces_IConfigurationHealthChecks_ValidateConfigurationsAsync_System_String_
  name: ValidateConfigurationsAsync
  nameWithType: IConfigurationHealthChecks.ValidateConfigurationsAsync
  fullName: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateConfigurationsAsync
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: FoundationaLLM.Common.Exceptions.ConfigurationValidationException
  commentId: T:FoundationaLLM.Common.Exceptions.ConfigurationValidationException
  href: FoundationaLLM.Common.Exceptions.ConfigurationValidationException.html
  name: ConfigurationValidationException
  nameWithType: ConfigurationValidationException
  fullName: FoundationaLLM.Common.Exceptions.ConfigurationValidationException
- uid: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateKeyVaultSecretsAsync*
  commentId: Overload:FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateKeyVaultSecretsAsync
  href: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.html#FoundationaLLM_Configuration_Interfaces_IConfigurationHealthChecks_ValidateKeyVaultSecretsAsync_System_String_
  name: ValidateKeyVaultSecretsAsync
  nameWithType: IConfigurationHealthChecks.ValidateKeyVaultSecretsAsync
  fullName: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateKeyVaultSecretsAsync
- uid: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateEnvironmentVariables*
  commentId: Overload:FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateEnvironmentVariables
  href: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.html#FoundationaLLM_Configuration_Interfaces_IConfigurationHealthChecks_ValidateEnvironmentVariables
  name: ValidateEnvironmentVariables
  nameWithType: IConfigurationHealthChecks.ValidateEnvironmentVariables
  fullName: FoundationaLLM.Configuration.Interfaces.IConfigurationHealthChecks.ValidateEnvironmentVariables
