name: Daily End to End Testing

on:
  workflow_dispatch: {}

jobs:
  daily_e2e_test:
    uses: ./.github/workflows/e2e-testing.yml
    with:
      environment: "fllm-e2e-aca-daily-${{ github.run_id }}"
      deployOpenAi: true
      openAiName: fllm-01
      openAiResourceGroup: fllm-shared-01
      location: EastUS
      notificationsEnabled: true
      enableTeardown: true
      bypassAndTeardown: false
      target: e2e
      deployAMLResources: false
    secrets: inherit
